### ISSUE TITLE
Project management matters

### ISSUE THREAD

**Issue by HolmesJJ** [AY2122S1-CS2103T-F12-4/tp#4]
### Links
I set up the milestones on our tp in origination, remember to check the deadline for each milestone.
**We only can implement functions during v1.2 and v1.3. (Now is v1.1)**
https://github.com/AY2122S1-CS2103T-F12-4/tp/milestones

I set up the labels for our issues and pull requests on our tp in origination
https://github.com/AY2122S1-CS2103T-F12-4/tp/labels

Project Folder
https://drive.google.com/drive/u/1/folders/1SNXqTZQa648i7KS61EjxL44xXK8gTx21

### Project functions implementation:
1. Fork the project to your personal github account
2. Create issue to represent project tasks at origination repo for the function that you are going to implement (add the link, add milestones, projects, at the right side of the issue page)
3. Create a pull request to our tp in origination: https://github.com/AY2122S1-CS2103T-F12-4/tp for the function at step 2
    a. **Tag your pull request type**
    c. **Link this pull request to the issue at step 2 (add the link, milestones at the right side of the pull request page)**
    c. add key word like "close""fix", etc. at your pull request description
4. Implement functions at **a separate branch of your local repo**, **branch name start with "branch-"**

### Notes:
1. Try to implement **test cases** for each of your new functions as many as possible, try to cover 90% functions (From prof expectation)
2. Try to minimum the size of each commit
3. All the ready pull request should be bug fix
4. Follow the **comment style and code style** like iP
5. **Bug free** is most important key point in tP, our PE is highly related to this
6. New updating need to be implemented **at a separate branch of your local repo**
7. All of us can do code review for all the pull requests
8. If there are any request is ready just @HolmesJJ or @zzybluebell at your pull request description or telegram
9. Keep **pulling the latest version of the master**

### Todo:
- [x] Plan who is going to implement which features
- [x] Plan the next iteration [Link](https://nus-cs2103-ay2122s1.github.io/website/schedule/week7/project.html#5-plan-the-next-iteration)
- [x] Check whether the reservations that have expired need to be marked
- [x] Check whether the current data need to be back up when clearing the program (UG)
- [x] Update the hyperlink of the GitHub logo on the upper left corner
- [x] Update the home page [Link](https://ay2122s1-cs2103t-f12-4.github.io/tp/)
- [x] Divide documentation work among team members equally; preferably based on enhancements/features each person would be adding (Add your name below the feature if your added this feature) [Link](https://nus-cs2103-ay2122s1.github.io/website/schedule/week7/project.html#3-update-the-ug)
- [x] check addressbook keywords in the whole project
    * address book
    * addressbook
    * addressbook ab
    * ab
    * ab-3
    * address-book
    * addressbook.json
    * addressbook-level3
- [x] check all the hyperlink to make sure they are not broken
- [x] seedu.address, person -> member
- [x] add member need to check the member id is full
- [x] add json description (UG)
- [x] run test coverage report
- [x] Need to fix one bug for the transaction, using set will cause comparing errors for the different transaction objects with the same amount. And this is not the proper way to add transactions and calculate the sum, need to check if the sum will overflow.
- [x] update -> edit; search -> find
- [x] reservation time should be future time (UG)
- [x] fix AddCommandPrefixParser parse
- [x] error message for billing, credit, point, etc should be positive number
- [x] run add -txn -b 1.00 -id 10002 after find -m -id 10001 will throw error
- [x] beautify UI
- [x] Some issues:
    * Transaction
    * AddCommand
    * requireNonNull
    * createUpdatedCredits
    * assert
    * updatedBilling
    * import seedu.address.model.reservation.Id;
    * Add Reservation at the same day
- [x] When delete transaction point performance
- [x] Adding a member : add -mem/
- [x] Show that phone email id cannot be replied (UG)
- [x] Big integer
- [x] different language (UG)
- [x] remove page feature (UG)
- [x] Update the MainWindows don't show all member details
- [x] You can reach us via email, as indicated below. (About)
- [x] code quality for summary
- [x] max billing, credit, point, number of member, transaction, reservation, index number (UG)
- [x] Only one reservation can be added within the same day
- [x] keyword not including prefix (UG)
- [x] point will be made up if gaven less, deduct if gaven more (UG)
- [x] Update UI.png
- [x] id 10001100001 (UG)
- [x] HD Logo (UG)
- [x] update HelpWindow content
- [x] update readme and ug image
- [x] same member cannot have multiple reservations in the same day
- [x] help box member id tran id
- [x] find can be multiple keywords (UG)
- [x] esc exit window (UG)
- [x] Update a password -> Set Password (UG)
- [x] summary Add, Delete Reservation, Reservation space, all edit delete Reservation id front (UG)
- [x] Point 4 maybe need another screenshot for the first launch (UG)
- [x] retrieve commands up to 30 records (UG)
- [x] Seat Booking Information should be coming (UG)
- [x] Requirements of input command bold and can be warning box, ONLY USED IN SORT COMMAND no need to upper case and it is too big (UG)
- [x] English language based user can bold (UG)
- [x] redeem -f (UG)
- [x] start from 00001
- [x] full stop
- [x] sort -mem/ -c/ -a/
- [x] icon lowcase
- [x] user? staff?
- [x] send email to us (UG)
